name: PR Workflow 002
run-name: ${{github.actor}} open pull request from ${{github.head_ref}} to ${{github.base_ref}}
on:
  pull_request:
    branches:
      - main

jobs:
  testing_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dir
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}

      - name: Set up Node.js 20.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.1

      - name: install dependencies
        run: npm install

      - name: Run main.js on assets
        run: node ./assets/hello.js

      - name: Running test cases
        run: node --test
        working-directory: .