name: Push Workflow 001
run-name: ${{github.actor}} running test on platform
on:
  push:
    branches:
      - main

jobs:
  testing_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dir
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Node.js 20.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.1

      - name: install dependencies
        run: npm install

      - name: Run main.js on assets
        run: node ./assets/hello.js

      - name: Running test cases
        run: node --test
        working-directory: .