name: test
run-name: ${{github.actor}} running test on platform
on:
  push:
    branches:
      - main

jobs:
  testing_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dir
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Node.js 16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Run main.js on assets
        run: node ./assets/hello.js